# Generated by Django 4.2.4 on 2023-08-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.IntegerField(),
        ),
    ]
